// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAASiUhv59_0ftV8ogpKmJz6uSKIsbc_co',
    appId: '1:898910550009:web:8d3914225fdb9c32f96f28',
    messagingSenderId: '898910550009',
    projectId: 'maternity-app-2ddc2',
    authDomain: 'maternity-app-2ddc2.firebaseapp.com',
    storageBucket: 'maternity-app-2ddc2.firebasestorage.app',
    measurementId: 'G-EJ85VRELS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUV1WeEvfMxARwqmokBZoHhFeGhr92nfo',
    appId: '1:898910550009:android:2d2e048a6bbeda4af96f28',
    messagingSenderId: '898910550009',
    projectId: 'maternity-app-2ddc2',
    storageBucket: 'maternity-app-2ddc2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHNuC9CUWu-xy7dUclGvczndyewHy_frw',
    appId: '1:898910550009:ios:5b9c49c774173b42f96f28',
    messagingSenderId: '898910550009',
    projectId: 'maternity-app-2ddc2',
    storageBucket: 'maternity-app-2ddc2.firebasestorage.app',
    iosBundleId: 'com.example.maternityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHNuC9CUWu-xy7dUclGvczndyewHy_frw',
    appId: '1:898910550009:ios:5b9c49c774173b42f96f28',
    messagingSenderId: '898910550009',
    projectId: 'maternity-app-2ddc2',
    storageBucket: 'maternity-app-2ddc2.firebasestorage.app',
    iosBundleId: 'com.example.maternityApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAASiUhv59_0ftV8ogpKmJz6uSKIsbc_co',
    appId: '1:898910550009:web:addd2ed673277c49f96f28',
    messagingSenderId: '898910550009',
    projectId: 'maternity-app-2ddc2',
    authDomain: 'maternity-app-2ddc2.firebaseapp.com',
    storageBucket: 'maternity-app-2ddc2.firebasestorage.app',
    measurementId: 'G-RYKF27ESH6',
  );
}
